parameters:
  env(TURBOLINKS_ENABLED): false
  turbolinks.enabled: "%env(bool:TURBOLINKS_ENABLED)%"

services:
  kunstmaan_admin.versionchecker:
    class: Superrb\KunstmaanAddonsBundle\VersionCheck\VersionChecker
    arguments: ["@service_container", "@kunstmaan_admin.cache", "@translator"]
    public: true

  kunstmaan_addons.turbolinks_location_subscriber:
    class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
    arguments: ["@session", "%turbolinks.enabled%"]
    public: true
    tags:
      - "kernel.event_subscriber"

  placeholder_image_filter:
    class: Superrb\KunstmaanAddonsBundle\Service\PlaceholderImage
    tags:
      - { name: "liip_imagine.filter.loader", loader: placeholder_image }

  kunstmaan_addons.twig.extension:
    class: Superrb\KunstmaanAddonsBundle\Extension\TwigExtension
    tags:
      - "twig.extension"
