parameters:
  env(TURBOLINKS_ENABLED): false
  recaptcha.enabled: "%env(bool:RECAPTCHA_ENABLED)%"
  turbolinks.enabled: "%env(bool:TURBOLINKS_ENABLED)%"

services:
  kunstmaan_addons.turbolinks_location_subscriber:
    class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
    arguments:
      - "@request_stack"
      - "%turbolinks.enabled%"
      - ['/^\/media/', '/^\/uploads/', '/^\/admin/']

    public: true
    tags:
      - "kernel.event_subscriber"

  placeholder_image_filter:
    class: Superrb\KunstmaanAddonsBundle\Service\PlaceholderImage
    tags:
      - { name: "liip_imagine.filter.loader", loader: placeholder_image }

  kunstmaan_addons.twig.extension:
    class: Superrb\KunstmaanAddonsBundle\Extension\TwigExtension
    arguments:
      $moneyRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\MoneyRenderer'
      $booleanRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\BooleanRenderer'
      $linkableEntityRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\LinkableEntityRenderer'
      $countryRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\CountryRenderer'
    tags:
      - "twig.extension"

  Superrb\KunstmaanAddonsBundle\Renderer\MoneyRenderer:
    public: true

  Superrb\KunstmaanAddonsBundle\Renderer\BooleanRenderer:
    public: true

  Superrb\KunstmaanAddonsBundle\Renderer\LinkableEntityRenderer:
    public: true
    arguments:
      $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'
      $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
      $translator: '@Symfony\Contracts\Translation\TranslatorInterface'

  Superrb\KunstmaanAddonsBundle\Renderer\CountryRenderer:
    public: true
    arguments:
      $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'

  Superrb\KunstmaanAddonsBundle\Service\MailerService:
    public: true
    arguments:
      $mailer: '@Symfony\Component\Mailer\MailerInterface'
      $templating: '@Twig\Environment'
      $translator: '@Symfony\Contracts\Translation\TranslatorInterface'
      $logger: '@Psr\Log\LoggerInterface'
      $emailFrom: "%enquiryfrom%"
      $emailBcc: "%enquirybcc%"

  Superrb\KunstmaanAddonsBundle\Form\Frontend\AbstractFrontendFormType:
    public: true
    arguments:
      $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
      $recaptchaFlagService: '@Superrb\KunstmaanAddonsBundle\Service\RecaptchaFlagService'

  Superrb\KunstmaanAddonsBundle\Service\RecaptchaFlagService:
    public: true
    arguments:
      $recaptchaEnabled: '%recaptcha.enabled%'

  kunstmaan_media.command.warmLiipImagineCacheCommand:
    class: Superrb\KunstmaanAddonsBundle\Command\WarmLiipImagineCacheCommand
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: console.command }
