parameters:
    env(TURBOLINKS_ENABLED): false
    turbolinks.enabled: "%env(bool:TURBOLINKS_ENABLED)%"
    database_proto: "%env(string:DATABASE_PROTO)%"
    database_host: "%env(resolve:DATABASE_HOST)%"
    database_port: "%env(int:DATABASE_PORT)%"
    database_user: "%env(string:DATABASE_USER)%"
    database_pass: "%env(string:DATABASE_PASS)%"
    database_name: "%env(string:DATABASE_NAME)%"
    database_extra: "%env(string:DATABASE_EXTRA)%"

services:
    kunstmaan_admin.versionchecker:
        class: Superrb\KunstmaanAddonsBundle\VersionCheck\VersionChecker
        arguments: ["@service_container", "@kunstmaan_admin.cache"]
        public: true

    kunstmaan_addons.turbolinks_location_subscriber:
        class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
        arguments: ["@session", "%turbolinks.enabled%"]
        public: true
        tags:
            - "kernel.event_subscriber"

    kunstmaan_addons.session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - "mysql:dbname=%database_name%; host=%database_host%; port=%database_port%"
            - {
                  db_username: "%database_user%",
                  db_password: "%database_pass%",
              }
        public: true

    placeholder_image_filter:
        class: Superrb\KunstmaanAddonsBundle\Service\PlaceholderImage
        tags:
            - { name: "liip_imagine.filter.loader", loader: placeholder_image }
