services:
    kunstmaan_admin.versionchecker:
        class: Superrb\KunstmaanAddonsBundle\VersionCheck\VersionChecker
        arguments: ["@service_container", "@kunstmaan_admin.cache"]
        public: true

    kunstmaan_addons.turbolinks_location_subscriber:
        class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
        arguments: ["@session"]
        public: true
        tags:
            - "kernel.event_subscriber"
