parameters:
    env(TURBOLINKS_ENABLED): false
    turbolinks.enabled: "%env(bool:TURBOLINKS_ENABLED)%"

services:
    kunstmaan_admin.versionchecker:
        class: Superrb\KunstmaanAddonsBundle\VersionCheck\VersionChecker
        arguments: ["@service_container", "@kunstmaan_admin.cache"]
        public: true

    kunstmaan_addons.turbolinks_location_subscriber:
        class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
        arguments: ["@session", "%turbolinks.enabled%"]
        public: true
        tags:
            - "kernel.event_subscriber"
